services:
  ros:
    build:
      context: ..
      dockerfile: devenv/Dockerfile
      args:
        - MY_UID=${MY_UID:-1000}
        - MY_GID=${MY_GID:-1000}
        - MY_USER=${MY_USER:-dev}
    environment:
      - DISPLAY=novnc:0.0
      - QT_X11_NO_MITSHM=1
    user: "${MY_UID:-1000}:${MY_GID:-1000}"
    depends_on:
      - novnc

  novnc:
    image: theasp/novnc:latest
    ports:
      - "8080:8080"
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
