name: Build Devcontainer

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'v2'
    paths:
      - .github/workflows/build-devenv.yaml
      - 'devenv/**'
      - '.devcontainer/**'
      - 'src/**/package.xml'
  pull_request:
    branches:
      - 'main'
    paths:
      - .github/workflows/build-devenv.yaml
      - 'devenv/**'
      - '.devcontainer/**'
      - 'src/**/package.xml'

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/open_mower_ros-devenv
          flavor: |
            latest=auto
          tags: |
            type=edge,branch=main
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./devenv/Dockerfile
          build-args: |
            MY_UID=1000
            MY_GID=1000
            MY_USER=dev
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: devenv
          cache-from: type=gha,scope=devenv
          cache-to: type=gha,scope=devenv,mode=max
